import sys #use of sys module to [perform system level operations

a = 1;          #integer...
b = 2;          #integer...
c = "harry";    #strings...
d = 71.42;      #floating...
e = False;      #boolean...
f = None; 
g ='h';      #none type variable....*imp*

print("size of integer : " , sys.getsizeof(a));
print("size of float : " , sys.getsizeof(d));
print("size of string : " , sys.getsizeof(c));
print("size of bool : " , sys.getsizeof(e));
print("size of none : " , sys.getsizeof(f));
print("size of h : " , sys.getsizeof(g));
