'''        variables    '''
# a ,b ,c ,d are => identifiers 

a = 1;          #integer...
b = 2;          #integer...
c = "harry";    #strings...
d = 71.42;      #floating...
e = False;      #boolean...
f = None;       #none type variable....*imp*
#print(a+b);

